name: Swift Build & Test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - name: Check Swift version
      run: swift --version

    - name: Build
      run: swift build

    - name: Run tests
      run: swift test
